# https://www.home-assistant.io/docs/automation/condition/
# https://www.home-assistant.io/docs/scripts/conditions/
- alias: 'Blind, kitchen close sunset'
  id: '27ffd9b2-713d-4468-8199-0780ad5ab4b3'
  trigger:
  - platform: sun
    event: sunset
    offset: "00:00:05"
  condition:
  - not:
    - condition: state
      entity_id: binary_sensor.kitchen_window_state
      state: 'on'
  action:
  - action: cover.close_cover
    entity_id: cover.kitchen

- alias: 'Blind, kitchen open sunrise'
  id: '44a80f7f-3623-4bfa-bc22-089deca0f1fe'
  trigger:
  - platform: sun
    event: sunrise
    offset: "00:00:05"
  action:
  - action: cover.open_cover
    entity_id: cover.kitchen