# https://www.home-assistant.io/docs/scripts/#choose-a-group-of-actions
- alias: 'Blind, lounge northeast close sunset'
  id: 'd0f2f385-a506-49f0-aeb0-7a25db6484be'
  trigger:
  - platform: sun
    event: sunset
    offset: "00:00:20"
  action:
  - service: cover.close_cover
    entity_id: cover.lounge_north_east

- alias: 'Blind, lounge northeast open sunrise'
  id: 'd4185ff5-7d96-49f4-aa26-a259c2a2f359'
  trigger:
  - platform: sun
    event: sunrise
    offset: "00:00:20"
  action:
  - service: cover.open_cover
    entity_id: cover.lounge_north_east