- alias: 'Blind, master bedroom close sunset'
  id: 'f2fc9964-0afe-44c9-8566-7c4cefbb03e9'
  trigger:
  - platform: sun
    event: sunset
    offset: "00:00:15"
  condition:
  - condition: state
    entity_id: binary_sensor.master_bedroom_window_state
    state: 'off'
  action:
  - service: cover.close_cover
    entity_id: cover.bedroom_master

- alias: 'Blind, master bedroom open sunrise'
  id: '21661e69-6f05-4bf7-97f7-def0a1c091c1'
  trigger:
  - platform: sun
    event: sunrise
    offset: "00:00:15"
  action:
  - service: cover.open_cover
    entity_id: cover.bedroom_master