# https://www.home-assistant.io/docs/scripts/#choose-a-group-of-actions
- alias: 'Blind, lounge southeast close sunset'
  id: '5ab8bedb-8aa4-44ec-8df0-5f642604aa82'
  trigger:
  - platform: sun
    event: sunset
    offset: "00:00:10"
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_boolean.holiday
              state: 'on'
          sequence:
            - service: cover.close_cover
              entity_id: cover.lounge_south_east
    - choose:
        - conditions:
            - condition: state
              entity_id: group.any_alarm_users_home
              state: 'not_home'
          sequence:
            - service: cover.close_cover
              entity_id: cover.lounge_south_east

- alias: 'Blind, lounge southeast close 23:00'
  id: '1379f32b-b39e-48b0-be25-637f6545692b'
  trigger:
  - platform: time
    at: 
        - "23:00:00"
        - "23:30:00"
        - "23:59:00"
  action:
  - service: cover.close_cover
    entity_id: cover.lounge_south_east

- alias: 'Blind, lounge southeast open sunrise'
  id: '482c85eb-8b80-4e96-adfc-73f5d85e3609'
  trigger:
  - platform: sun
    event: sunrise
    offset: "00:00:10"
  action:
  - service: cover.open_cover
    entity_id: cover.lounge_south_east