# https://www.home-assistant.io/docs/scripts/#choose-a-group-of-actions
- alias: 'Blind, dining northwest close sunset'
  id: 'f3b53acd-0945-4627-9469-15a75828a432'
  trigger:
  - platform: sun
    event: sunset
    offset: "00:00:25"
  action:
  - service: cover.close_cover
    entity_id: cover.dining_north_west

- alias: 'Blind, dining northwest open sunrise'
  id: '92cb6671-b329-4ba7-bb2f-a4b26171008a'
  trigger:
  - platform: sun
    event: sunrise
    offset: "00:00:25"
  action:
  - service: cover.open_cover
    entity_id: cover.dining_north_west