- alias: 'Pi-Hole, switch off for 5 minutes'
  id: '67500502-8a0d-49c5-ae95-91dcf855e7bb'
  trigger:
    - platform: state
      entity_id: input_button.disable_pihole
  action:
    - service: pi_hole.disable
      data:
        duration: '00:05'
      target:
        entity_id: all