- alias: "Arm alarm when everyone Left"
  id: '42575320-5d8e-4223-8f6f-a83f1c2a77a4'
  trigger:
    - platform: state
      entity_id: group.any_alarm_users_home
      to: "not_home"
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - service: alarm_control_panel.alarm_arm_away
      target:
        entity_id: alarm_control_panel.intrusion_alarm
