- alias: 'Alarm, trigger alarm while armed away'
  id: '9b46a0f4-96aa-4aa6-b520-de4882fdb915'
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion_3
      to: "on"
    - platform: state
      entity_id: binary_sensor.garage_motion
      to: "on"
    - platform: state
      entity_id: binary_sensor.kitchen_motion
      to: "on"
    - platform: state
      entity_id: binary_sensor.hallway_motion
      to: "on"
    - platform: state
      entity_id: binary_sensor.north_window_left_state
      to: "on"
    - platform: state
      entity_id: binary_sensor.north_window_right_state
      to: "on"
    - platform: state
      entity_id: binary_sensor.master_bedroom_window_state
      to: "on"
    - platform: state
      entity_id: binary_sensor.kitchen_window
      to: "on"
    - platform: state
      entity_id: binary_sensor.alarm_motion_garage
      to: "on"
    - platform: state
      entity_id: binary_sensor.garage_roller_door_external_input
      to: "off"
  condition:
    - condition: state
      entity_id: alarm_control_panel.intrusion_alarm
      state: armed_away
  action:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.trigger_source
        value: "{{ trigger.to_state.attributes.friendly_name }}"
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.intrusion_alarm
# https://community.home-assistant.io/t/notification-to-state-which-sensor-triggered-manual-alarm/146071/7

