- alias: "Presence when everyone left"
  id: '272fab25-79e9-49d6-8721-47b1d093fd3e'
  trigger:
    - platform: state
      entity_id: group.any_alarm_users_home
      to: "not_home"
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'  
  action:
    - service: remote.turn_on
      data:
        entity_id: remote.media_centre
        activity: 'PowerOff'
    - service: switch.turn_on
      data:
        entity_id: switch.dining_outlet_switch